.gitignore
integration-test/__snapshots__/import.integration-test.ts.snap
integration-test/data/codes/codes.xml
integration-test/data/error/ambiguous/income.xml
integration-test/data/error/empty/incomerows.xml
integration-test/data/error/nonflat/codes.xml
integration-test/data/error/unknowncolumn/person.xml
integration-test/data/error/unknowncolumn/persons.xml
integration-test/data/error/unknowntable/notarealtable.xml
integration-test/data/families/families.xml
integration-test/data/income/income.xml
integration-test/data/incomerows/incomerows.xml
integration-test/data/mixedcase/codes.xml
integration-test/data/person/person.xml
integration-test/data/persons/persons.xml
integration-test/import.integration-test.ts
package-lock.json
package.json
src/app.ts
src/config.ts
src/io.ts
src/mapping.ts
src/parsers.ts
src/service.ts
src/types.ts

- Modified file content expectations according to real data test findings
- Added case insensitivity to file intake
- Fixed snapshot testing
- Amended integration tests with above changes and case sensitivity test case

TREV-188: Making parser compatible with actual Effica-data

---

src/mapping.ts

- Table mappings for majority of Effica-data in the data dumps
- some improvements to type parsers to better process Effica-style code values
- all additions tested to work with data dumps

TREV-187: Expand table mappings to cover most of required Effica-data

---

integration-test/__snapshots__/import.integration-test.ts.snap
integration-test/data/childminders/childminders.xml
integration-test/data/codes/codes.xml
integration-test/data/decisions/decisions.xml
integration-test/data/departments/departments.xml
integration-test/data/families/families.xml
integration-test/data/feedeviations/feedeviations.xml
integration-test/data/person/person.xml
integration-test/data/placementextents/placementextents.xml
integration-test/data/placements/placements.xml
integration-test/data/units/units.xml
integration-test/import.integration-test.ts
package.json
src/api/import.ts
src/db/db.ts
src/mapping.ts
src/parsers.ts
src/service.ts

- table mapping now has current scope of migration data
- tests cover all mapped tables
- refactoring and cleanup

TREV-216: More tests and test refactoring

---

integration-test/__snapshots__/import.integration-test.ts.snap
integration-test/__snapshots__/transform.integration-test.ts.snap
integration-test/data/incomerows/incomerows.xml
integration-test/data/mixedcase/codes.xml
integration-test/import.integration-test.ts
integration-test/transform.integration-test.ts
src/api/transform.ts
src/config.ts
src/mapping/citySpecific.ts
src/mapping/coefficients.ts
src/transform/income.ts
src/types/mappings.ts
src/util/queryTools.ts

- Income transformation logic based on Espoo scripting
- city specific variation for Effica-Evaka income mappings
- test data changes to make the data TRE compatible
- integration test for transforming income data
- test facility fix for deadlock issue upon clean up
- NOTE: income mappings are incomplete and require further discussions with evaka core-team and TRE effica specialists

TREV-248: first draft of income transformation

---

integration-test/transform.integration-test.ts
src/db/common.ts
src/db/effica.ts
src/db/evaka.ts
src/transform/application.ts
src/transform/departments.ts
src/transform/families.ts
src/transform/income.ts
src/transform/person.ts
src/util/queryTools.ts
src/util/testTools.ts

- Added evaka db restrictions to parser transformation tables to catch anomalous data earlier
- updated test setup requirements for transformations
- refactored test setup and cleanup to work more reliably
- renamed config value getters to prefix getters in order to highlight their inteded use

TREV-283: Add evaka constraints, defaults and restrictions

---

integration-test/__snapshots__/import.integration-test.ts.snap
integration-test/data/applicationrows/applicationrows.xml
integration-test/data/applications/applications.xml
integration-test/transform.integration-test.ts
src/constants.ts
src/db/effica.ts
src/db/evaka.ts
src/transform/application.ts
src/types/effica.ts
src/types/evaka.ts

Multiple fixes to application transform. Checking commits separately might be a good idea.

Application transform fixes

---

integration-test/__snapshots__/import.integration-test.ts.snap
integration-test/__snapshots__/transfer.integration-test.ts.snap
integration-test/__snapshots__/transform.integration-test.ts.snap
integration-test/data/paydecisionrows/paydecisionrows.xml
integration-test/data/paydecisions/paydecisions.xml
integration-test/import.integration-test.ts
integration-test/transfer.integration-test.ts
integration-test/transform.integration-test.ts
src/api/transfer.ts
src/api/transform.ts
src/mapping/citySpecific.ts
src/mapping/sourceMapping.ts
src/transfer/fee-decisions.ts
src/transform/pay-decisions.ts
src/types/mappings.ts
src/util/error.ts
src/util/sql/transfer-fee-decision.sql
src/util/sql/transform-pay-decision.sql

Also fixes some type errors (https://github.com/Tampere/effica-trevaka-parser/commit/0118fda8e59cac3480385dcff469efdf4dc6f011 & https://github.com/Tampere/effica-trevaka-parser/commit/22ab1d70d59f39324ac1d62ece0867a1f18af9dd)

Add initial pay decisions migration

---

src/api/import.ts
src/import/service.ts
src/mapping/citySpecific.ts
src/types/internal.ts
src/util/sql/import-fixes/tampere/families-post-import-fix.sql

- endpoint for running fix scripts per configured city variant
- families fix script for resolving conflicts in Effica-data for Tampere

TREV-415: Added mechanism for post-import fixes per city variant

---

Dockerfile-it-db
integration-test/__snapshots__/import.integration-test.ts.snap
integration-test/data/families/families.xml
integration-test/data/families_exclusion/families_exclusion.csv
integration-test/data/families_exclusion/families_exclusion.csv.license
integration-test/import.integration-test.ts
integration-test/transfer.integration-test.ts
integration-test/transform.integration-test.ts
src/config.ts
src/db/evaka.ts
src/import/service.ts
src/io/io.ts
src/mapping/sourceMapping.ts
src/transform/families.ts
src/types.ts
src/util/sql/import-fixes/tampere/families-post-import-fix.sql
src/util/testTools.ts

- a mechanism for configuring and creating an exclusion table for any Effica source table
- implementation for excluding family data (families table)
- integration test for family data exclusion

TREV-414: Exclusion mechanism

---

README.md
src/api/maintenance.ts
src/app.ts
src/db/evaka.ts

- refactored eVaka data reset to common maintenance route
- added an endpoint for running a VACUUM ANALYZE task for a list of eVaka tables
- updated documentation

TREV-416: Maintenance endpoint to run VACUUM ANALYZE for affected eVaka tables

---

src/util/sql/transform-timestamps.sql

Add timestamps rowtype filter

---

src/api/transfer.ts
src/api/transform.ts
src/mapping/sourceMapping.ts

- enabled mass operations for latest migration targets
- assistance need and action
- child attendance
- added name field for unitmap source mapping

Mass update changes

---

src/mapping/citySpecific.ts
src/transform/voucher-value-decisions.ts
src/util/sql/transform-voucher-value-decision.sql

This should remove all 'STATUS MISSING' todos.

Fix ignored voucher value decisions by status

---

integration-test/__snapshots__/transform.integration-test.ts.snap
src/api/transfer.ts
src/util/sql/transform-daily-journal.sql
src/util/sql/transform-timestamps.sql

- included new select columns for attendance debugging
- fixed category issue preventing absence migration
- added new TODO collection to differentiate attendance overlap issues

Dataset update changes

---

integration-test/__snapshots__/transfer.integration-test.ts.snap
integration-test/__snapshots__/transform.integration-test.ts.snap
src/transfer/child-attendances.ts
src/util/sql/transfer-child-attendance.sql
src/util/sql/transform-timestamps.sql

Fix child attendance transfer

---

integration-test/__snapshots__/transform.integration-test.ts.snap
src/mapping/citySpecific.ts
src/transform/placements.ts
src/util/sql/transform-placement.sql

- erho-unit placement end date assignments are handled separately
- end date set to day before child's 18th birthday if empty in Effica data
- Tampere city variant configuration for erho unit codes

Erho placement fix

---

integration-test/__snapshots__/transform.integration-test.ts.snap
integration-test/transfer.integration-test.ts
src/api/transfer.ts
src/api/transform.ts
src/util/sql/transfer-application.sql
src/util/sql/transform-placement.sql

This should fix both migrated and existing transfer applications.

Fix transfer applications

---

src/mapping/citySpecific.ts
src/transform/daily-journals.ts
src/transform/timestamps.ts
src/types/mappings.ts
src/util/sql/transform-daily-journal.sql
src/util/sql/transform-placement.sql
src/util/sql/transform-timestamps.sql

- configurable selection period for markings data, initial period ending 2022-02-28
- filtering based on selection period (absence, attendance, backup-care) in transformation queries

Selection period

---

src/transfer/departments.ts
src/transform/person.ts

- copy only persons with an ssn
- correct source table for group information in order to avoid conflicts

Added quick fixes for 2 issues found during prod migration

---

README.md
src/api/varda.ts
src/app.ts
src/config.ts
src/types/mappings.ts
src/util/varda-client.ts

- added parser API for Varda-client operations, rudimentary mapping check
- documentation

Varda checks API and documentation

---

.reuse/dep5
.run/Template Jest.run.xml
bin/add-license-headers.sh

Settings from package.json integration-test script.

Add IDEA run configuration to be able to test from IDE

---

integration-test/__snapshots__/transform.integration-test.ts.snap
integration-test/import.integration-test.ts
integration-test/transfer.integration-test.ts
integration-test/transform.integration-test.ts
integration-test/varda.integration-test.ts
src/transform/placements.ts
src/util/testTools.ts

Add cleanup db for tests

---

src/index.ts

Broken from a0c3f48c70a5adac6085661b55a3ddb957c74d13.

Fix startup
